services:
  app-test:
    image: backuporganizer_app:test
    build:
      context: .
      target: test
    volumes:
     - ./src:/app/src
     - ./tests:/app/tests
    ports:
     - "5000:5000"
    environment:
     - FLASK_ENV=testing
     - FLASK_DEBUG=false
    command: pytest
    container_name: backuporganizer_app_test