services:
  app-dev:
    image: backuporganizer_app:dev
    build:
      context: .
      target: dev
    volumes:
     - ./src:/app/src
    ports:
     - "5000:5000"
    environment:
     - FLASK_ENV=development
     - FLASK_DEBUG=true
    container_name: backuporganizer_app_dev